-- Baseline schema for menD, matching the JPA entities under ai.devin.mend.domain.
--
-- Enum-backed columns are plain varchar and deliberately carry no CHECK constraint: adding a
-- state (UNVERIFIED and CHANGES_REQUESTED were both added after the first release) must be a
-- code change, never a schema change. They are sized well beyond the longest current value.

create table remediation_task (
    id                       bigint generated by default as identity primary key,
    repo                     varchar(255) not null,
    issue_number             integer not null,
    issue_title              varchar(1024),
    issue_url                varchar(255),
    issue_labels             varchar(512),
    state                    varchar(32) not null,
    criteria_json            clob,
    criteria_hash            varchar(255),
    criteria_session_id      varchar(255),
    criteria_session_url     varchar(255),
    session_id               varchar(255),
    session_url              varchar(255),
    verifier_session_id      varchar(255),
    verifier_session_url     varchar(255),
    retrospective_session_id varchar(255),
    pr_url                   varchar(255),
    ci_status                varchar(255),
    verification_tier        varchar(32),
    verification_json        clob,
    outcome_json             clob,
    feedback_json            clob,
    exclusion_reason         varchar(2048),
    last_error               varchar(2048),
    confidence               float(53),
    acu_budget               integer,
    attempts                 integer not null,
    nudges                   integer not null,
    review_rounds            integer default 0 not null,
    learnings_extracted      boolean default false not null,
    owner_id                 varchar(128),
    lease_expires_at         timestamp(6) with time zone,
    lease_acquired_at        timestamp(6) with time zone,
    lease_takeovers          integer default 0 not null,
    eta_at                   timestamp(6) with time zone,
    criteria_started_at      timestamp(6) with time zone,
    ready_at                 timestamp(6) with time zone,
    dispatched_at            timestamp(6) with time zone,
    pr_opened_at             timestamp(6) with time zone,
    contract_dispatched_at   timestamp(6) with time zone,
    last_review_at           timestamp(6) with time zone,
    last_polled_at           timestamp(6) with time zone,
    last_nudged_at           timestamp(6) with time zone,
    completed_at             timestamp(6) with time zone,
    created_at               timestamp(6) with time zone not null,
    updated_at               timestamp(6) with time zone not null,
    version                  bigint,
    unique (repo, issue_number)
);

create index idx_task_state on remediation_task (state);

create table task_event (
    id          bigint generated by default as identity primary key,
    task_id     bigint not null,
    task_key    varchar(255) not null,
    from_state  varchar(32),
    to_state    varchar(32) not null,
    actor       varchar(32) not null,
    reason      varchar(2048),
    occurred_at timestamp(6) with time zone not null
);

create index idx_event_task on task_event (task_id);

create table repository (
    owner                varchar(128) not null,
    name                 varchar(128) not null,
    id                   bigint generated by default as identity primary key,
    default_branch       varchar(128),
    installation_id      varchar(64),
    trigger_label        varchar(128),
    enabled              boolean default true not null,
    acu_budget           integer,
    access_state         varchar(32) not null,
    access_error         varchar(1024),
    access_checked_at    timestamp(6) with time zone,
    index_state          varchar(32) not null,
    index_error          varchar(1024),
    indexed_sha          varchar(64),
    indexed_at           timestamp(6) with time zone,
    commits_since_index  integer default 0 not null,
    context_session_id   varchar(128),
    context_session_url  varchar(512),
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    version              bigint,
    unique (owner, name)
);

create table repository_context (
    id            bigint generated by default as identity primary key,
    repository_id bigint not null,
    kind          varchar(32) not null,
    content       clob not null,
    source_sha    varchar(64),
    stale         boolean default false not null,
    updated_at    timestamp(6) with time zone not null,
    unique (repository_id, kind)
);

create index idx_context_repo on repository_context (repository_id);

create table learning (
    id                          bigint generated by default as identity primary key,
    scope                       varchar(16) not null,
    status                      varchar(16) not null,
    repo                        varchar(255),
    topic                       varchar(64),
    lesson                      clob not null,
    evidence                    clob,
    recommended_action          varchar(32),
    action_detail               clob,
    fingerprint                 varchar(64) unique,
    confidence                  float(53),
    source_repo                 varchar(255),
    source_issue                integer,
    source_pr_url               varchar(255),
    times_applied               integer default 0 not null,
    times_followed_by_feedback  integer default 0 not null,
    times_retired               integer default 0 not null,
    retired_before_promotion    boolean default false not null,
    last_applied_at             timestamp(6) with time zone,
    retired_at                  timestamp(6) with time zone,
    created_at                  timestamp(6) with time zone,
    updated_at                  timestamp(6) with time zone,
    version                     bigint
);

create index idx_learning_repo on learning (repo, status);
